# This is a basic workflow to help you get started with Actions

name: Check Changes
run-name: Deploy to ${{ github.ref }}
on:
  workflow_dispatch:
    inputs:
      in_env_name:
        type: string
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.in_env_name}}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cardinalby/git-get-release-action@v1
        id: latest-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      
      - name: Set the value
        run: |
          echo ${{ github.actor }}

      - name: Role
        if: contains('["mustafahawi","xxx"]', github.actor)
        run: |
          echo ${{ github.actor.role }}
          
      - name: Set the value
        run: |
          echo "latest_tag=${{ steps.latest-release.outputs.tag_name }}" >> $GITHUB_ENV
          
      - name: Prev commit
        run: |
          echo ${{ env.latest_tag }}
          OUTPUT=$(git rev-list -n 1 ${{ env.latest_tag }})
          echo "${OUTPUT}"
          echo "prev_commit=${OUTPUT}" >> $GITHUB_ENV

      - name: Prev commit display
        run: |
          echo ${{ env.prev_commit }}
          
      - name: Get changed files
        id: changed-files-1
        uses: tj-actions/changed-files@v33
        with:
          # sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ env.prev_commit }}
          files: |
            .github/**
            services 1/**
            common/**
            data-layer/**
            scripts/generate-config/**
            package.json
            package-lock.json

      - name: Run step if any of the listed files above change
        if: steps.changed-files-1.outputs.any_changed == 'true'
        run: |
          echo "Service 1"

      - name: Get changed files
        id: changed-files-2
        uses: tj-actions/changed-files@v33
        with:
          # sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ env.prev_commit }}
          files: |
            .github/**
            services 2/**
            common/**
            data-layer/**
            scripts/generate-config/**
            package.json
            package-lock.json

      - name: Run step if any of the listed files above change
        if: steps.changed-files-2.outputs.any_changed == 'true'
        run: |
          echo "Service 2"
