on:
  workflow_call:
    inputs:
      in_env_name:
        type: string
        required: true
      my:
        type: string
        required: true

env:
  MY_ENV_VALUE: ${{inputs.my}}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.in_env_name}}
    steps:            
      - name: Deploy
        run: echo "${{env.MY_ENV_VALUE}}"
      
      - name: Set up secret file
        run: |
          echo "${{env.MY_ENV_VALUE}}" >> secrets.txt
          echo $MY_ENV_VALUE >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2