on:
  workflow_call:
    inputs:
      in_env_name:
        type: string
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.in_env_name}}
    env:
      ENV_NAME: '${{ secrets.ENV_NAME }}'
    steps:      
      - name: env_name
        run: echo "${{inputs.in_env_name}}"

      - name: Deploy
        run: echo "${{env.STAGE}}"
      
      - name: Deploy
        run: echo "${{env.ENV_NAME}}"
      
      - name: Deploy
        run: echo "${{secrets.TEST_ENV}}"

      - name: Set up secret file
        env:
          STAGE: '${{ env.STAGE }}'
          MY_ENV_NAME: '${{ env.ENV_NAME }}'
        run: |
          echo $MY_ENV_NAME >> secrets.txt
          echo $STAGE >> secrets.txt

      - name: Run tmate
        env:
          ENV_NAME: '${{ secrets.ENV_NAME }}'
        uses: mxschmitt/action-tmate@v2
