on:
  workflow_call:
    secrets:
      envName:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Deploy
        run: echo "${{secrets.envName}}"
        
