on:
  workflow_call:
    secrets:
      envName:
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:      
      - name: Deploy
        run: echo "${{secrets.envName}}"
