on:
  workflow_call:
    inputs:
      envName:
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:      
      - name: Deploy
        run: echo "${{inputs.envName}}"
