on:
  workflow_call:
    inputs:
      env:
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{input.env}}
    steps:      
      - name: Deploy
        run: echo "${{secrets.env_name}}"
