on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    steps:      
      - name: Deploy
        run: echo "${{secrets.ENV_NAME}}"

    - name: Set up secret file
      env:
        ENV_NAME: ${{ secrets.ENV_NAME }}
      run: |
        echo $ENV_NAME >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
