on:
  workflow_call:
    inputs:
      in_env_name:
        type: string
        required: true
      my:
        type: string
        required: true

env:
  MY_ENV_VALUE: ${{inputs.my}}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.in_env_name}}
    env:
      ENV_NAME: '${{ secrets.ENV_NAME }}'
    steps:            
      - name: Deploy
        run: echo "${{env.MY_ENV_VALUE}}"
      
      - name: Set up secret file
        env:
        M_ENV_VALUE: '${{ env.MY_ENV_VALUE }}'
        run: |
          echo $M_ENV_VALUE >> secrets.txt
          echo $MY_ENV_VALUE >> secrets.txt

  build2:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.in_env_name}}
    env:
      ENV_NAME: '${{ secrets.ENV_NAME }}'
    steps:            
      - name: Deploy
        run: echo "${{env.MY_ENV_VALUE}}"
      
      - name: Set up secret file
        env:
        M_ENV_VALUE: '${{ env.MY_ENV_VALUE }}'
        run: |
          echo $M_ENV_VALUE >> secrets.txt
          echo $MY_ENV_VALUE >> secrets.txt
