on:
  workflow_call:
    inputs:
      in_env_name:
        type: string
        required: true
      drop_create_db:
        type: boolean
        default: false
      my:
        type: string
        required: true

env:
  SECRETS_MY_ENV_VALUE: ${{secrets.ENV_NAME}}
  

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{inputs.in_env_name}}
    steps:            
      - name: Deploy
        run: echo "${{env.SECRETS_MY_ENV_VALUE}}"
      
      - name: Set up secret file
        run: |
          echo "${{env.SECRETS_MY_ENV_VALUE}}" >> secrets.txt
          echo "${{env.ENV_NAME}}" >> secrets.txt
          echo "${{secrets.ENV_NAME}}" >> secrets.txt 
          echo $SECRETS_MY_ENV_VALUE >> secrets.txt
          
      - uses: mxschmitt/action-tmate@v2
