on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: '${{inputs.env}}'
    env:
      ENV_NAME: '${{ secrets.ENV_NAME }}'
    steps:      
      - name: env
        run: echo "${{inputs.env}}"

      - name: Deploy
        run: echo "${{env.ENV_NAME}}"

      - name: Set up secret file
        env:
          MY_ENV_NAME: '${{ env.ENV_NAME }}'
        run: |
          echo $MY_ENV_NAME >> secrets.txt

      - name: Run tmate
        env:
          ENV_NAME: '${{ secrets.ENV_NAME }}'
        uses: mxschmitt/action-tmate@v2
