# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  uat:
    uses: ./.github/workflows/deploy.yml
    needs: do
    with:
      env: 'uat'
     
  prod:
    uses: ./.github/workflows/deploy.yml
    needs: uat
    with:
      env: 'prod'
