# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

env:
  STAGE: live

jobs:
  uat:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      in_env_name: 'uat'
      drop_create_db: true
      my: 'Helllo uat'
     
  prod:
    uses: ./.github/workflows/deploy.yml
    needs: uat
    secrets: inherit
    with:
      in_env_name: 'prod'
      my: 'Helllo prod'
