# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  uat:
    environment: uat
    uses: mustafahawi/deployment-flow/.github/workflows/deploy.yml@main
    secrets:
      envName: ${{ secrets.envName }}

        
  prod:
    needs: uat
    environment: prod
    uses: mustafahawi/deployment-flow/.github/workflows/deploy.yml@main
    secrets:
      envName: ${{ secrets.envName }}
