# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  uat:
    uses: ./.github/workflows/deploy.yml
    environment: 
      name: uat
    secrets:
      envName:  ${{ secrets.env_name }}
     
  prod:
    uses: ./.github/workflows/deploy.yml
    needs: uat
    environment: 
      name: prod
    secrets:
      envName: ${{ secrets.env_name }}
      
