# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  uat:
    environment: 
      name: uat
    uses: ./.github/workflows/deploy.yml
    secrets:
      envName:  ${{ secrets.env_name }}

        
  prod:
    needs: uat
    environment: 
      name: prod
    uses: ./.github/workflows/deploy.yml
    secrets:
      envName: ${{ secrets.env_name }}
