# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  uat:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - uses: mustafahawi/deployment-flow/.github/workflows/deploy.yml@main
        with:
          envName: ${{ secrets.envName }}
        
  prod:
    runs-on: ubuntu-latest
    needs: uat
    environment: prod
    steps:
      - uses: mustafahawi/deployment-flow/.github/workflows/deploy.yml@main
        with:
          envName: ${{ secrets.envName }}
