# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  uat:
    uses: ./.github/workflows/deploy.yml
    with:
      envName: 'uat'

        
  prod:
    needs: uat
    uses: ./.github/workflows/deploy.yml
    with:
      envName: 'prod'
